package shim

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"regexp"
	"strconv"
	"strings"
)

// MarkerVersion is the current marker version of generated artifacts.
// Only known versions are deleted; a file written by a newer version is
// skipped rather than wrongly removed by an older ak.
const MarkerVersion = 1

// markerRe matches the marker line. The probe reads only the first few
// bytes to avoid pulling a large file into memory.
var markerRe = regexp.MustCompile(`^#\s*ak:generated v(\d+)(?:\s+(.*))?$`)

// probeBytes is the maximum number of bytes read when identifying the marker.
const probeBytes = 4096

// Marker is the metadata carried on the first line of a generated artifact.
type Marker struct {
	Version  int
	Kind     string
	Provider string
	Hash     string
}

// Line renders the marker line.
func (m Marker) Line() string {
	return fmt.Sprintf("# ak:generated v%d kind=%s provider=%s hash=%s",
		MarkerVersion, m.Kind, m.Provider, m.Hash)
}

// hashBody computes the body fingerprint, used to detect content changes
// (idempotency) and drift.
func hashBody(body string) string {
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:])[:16]
}

// readMarker tries to parse the marker from the file header.
// ok=false means this file was not generated by ak — callers must refuse
// to delete it in that case.
func readMarker(path string) (Marker, bool) {
	f, err := os.Open(path)
	if err != nil {
		return Marker{}, false
	}
	defer f.Close()

	buf := make([]byte, probeBytes)
	n, err := f.Read(buf)
	if n == 0 || (err != nil && err != io.EOF) {
		return Marker{}, false
	}
	head := buf[:n]

	// The marker must appear within the first few lines. Scan line by line
	// and stop at the first match.
	start := 0
	for line := 0; line < 5 && start < len(head); line++ {
		end := start
		for end < len(head) && head[end] != '\n' {
			end++
		}
		if m, ok := parseMarkerLine(string(head[start:end])); ok {
			return m, true
		}
		start = end + 1
	}
	return Marker{}, false
}

func parseMarkerLine(line string) (Marker, bool) {
	sub := markerRe.FindStringSubmatch(strings.TrimSuffix(line, "\r"))
	if sub == nil {
		return Marker{}, false
	}
	v, err := strconv.Atoi(sub[1])
	if err != nil {
		return Marker{}, false
	}
	m := Marker{Version: v}
	for _, kv := range strings.Fields(sub[2]) {
		k, val, ok := strings.Cut(kv, "=")
		if !ok {
			continue
		}
		switch k {
		case "kind":
			m.Kind = val
		case "provider":
			m.Provider = val
		case "hash":
			m.Hash = val
		}
	}
	return m, true
}
