package shim

import (
	"fmt"
	"strings"
)

// Spec describes a provider command to generate.
type Spec struct {
	Name string // Provider name, recorded in the marker
	Kind string
	// Target is what the command launches: <provider> or <provider>:<variant>.
	Target string
	// Self is ak's own path; ak on PATH is the fallback.
	Self string
}

const doNotEdit = "# DO NOT EDIT - generated by ak; changes are overwritten by the next `ak sync`.\n"

// shellQuote wraps the value in single quotes and escapes inner single quotes,
// making any content safe. Bash performs no expansion inside single quotes, so
// $ ` " \ and newlines all stay literal.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// script assembles a marked bash script around a body.
func script(kind, name, body string) string {
	m := Marker{Kind: kind, Provider: name, Hash: hashBody(body)}
	return "#!/usr/bin/env bash\n" + m.Line() + "\n" + doNotEdit + body
}

// withMarker prefixes a non-script artifact with the marker line.
func withMarker(kind, name string, body []byte) string {
	m := Marker{Kind: kind, Provider: name, Hash: hashBody(string(body))}
	return m.Line() + "\n" + doNotEdit + string(body)
}

// Render renders the provider command. It holds no launch logic and no key:
// it hands its arguments to `ak run`, so the command never drifts from the
// config and works the same as `ak <target>`.
func Render(s Spec) string {
	var b strings.Builder
	b.WriteString("set -euo pipefail\n\n")
	b.WriteString(assignWithOverride("ak_self", "AK_BIN", s.Self))
	b.WriteString("if [ ! -x \"$ak_self\" ]; then\n")
	b.WriteString("  ak_self=\"$(command -v ak || true)\"\n")
	b.WriteString("fi\n")
	b.WriteString("if [ -z \"$ak_self\" ]; then\n")
	b.WriteString("  echo 'ak: ak not found; check PATH or set AK_BIN' >&2\n")
	b.WriteString("  exit 127\n")
	b.WriteString("fi\n")
	fmt.Fprintf(&b, "exec \"$ak_self\" run %s \"$@\"\n", shellQuote(s.Target))
	return script(s.Kind, s.Name, b.String())
}

// assignWithOverride sets a variable to a default that an environment
// variable may override. The default is assigned on its own line: inside
// "${VAR:-'x'}" bash keeps the single quotes literally, which broke the path.
func assignWithOverride(name, envVar, def string) string {
	return fmt.Sprintf("%s=%s\nif [ -n \"${%s:-}\" ]; then %s=\"$%s\"; fi\n",
		name, shellQuote(def), envVar, name, envVar)
}
