package shim

import (
	"fmt"
	"strings"

	"github.com/abcdlsj/ak/internal/provider"
)

// Spec describes a provider command to generate.
type Spec struct {
	Name    string // Provider name
	Kind    string
	Bin     string // Absolute path of the pinned engine binary; empty means rely on PATH
	BinName string // Engine command name, used as the PATH fallback
	EnvVar  string // Environment variable that overrides Bin, e.g. AK_CLAUDE_BIN
	Launch  provider.Launch
	// Self is ak's own path, used to resolve a deferred key at run time.
	Self string
	// Pool marks a pool command, which starts the gateway if it is not up.
	Pool bool
}

const doNotEdit = "# DO NOT EDIT - generated by ak; changes are overwritten by the next `ak sync`.\n"

// shellQuote wraps the value in single quotes and escapes inner single quotes,
// making any content safe. Bash performs no expansion inside single quotes, so
// $ ` " \ and newlines all stay literal.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func shellWords(args []string) string {
	q := make([]string, len(args))
	for i, a := range args {
		q[i] = shellQuote(a)
	}
	return strings.Join(q, " ")
}

// script assembles a marked bash script around a body.
func script(kind, name, body string) string {
	m := Marker{Kind: kind, Provider: name, Hash: hashBody(body)}
	return "#!/usr/bin/env bash\n" + m.Line() + "\n" + doNotEdit + body
}

// withMarker prefixes a non-script artifact with the marker line.
func withMarker(kind, name string, body []byte) string {
	m := Marker{Kind: kind, Provider: name, Hash: hashBody(string(body))}
	return m.Line() + "\n" + doNotEdit + string(body)
}

// Render renders the provider command, returning the complete file.
func Render(s Spec) string {
	var b strings.Builder
	b.WriteString("set -euo pipefail\n\n")
	l := s.Launch

	if len(l.Variants) > 0 {
		// The first argument is consumed only on an exact variant match;
		// anything else is passed through, so `ak-x -p "..."` still works.
		names := make([]string, len(l.Variants))
		for i, v := range l.Variants {
			names[i] = v.Name
		}
		b.WriteString("# Variant: consume the first argument only on an exact match\n")
		if l.DefaultVariant != "" {
			fmt.Fprintf(&b, "# Default variant: applied unless the first argument is another variant\nak_variant=%s\n", shellQuote(l.DefaultVariant))
		} else {
			b.WriteString("ak_variant=\n")
		}
		b.WriteString("if [ $# -gt 0 ]; then\n")
		fmt.Fprintf(&b, "  case \"$1\" in\n    %s)\n      ak_variant=\"$1\"; shift ;;\n  esac\nfi\n\n",
			strings.Join(names, "|"))
	}

	// A nested launch inherits what the parent ak command exported; drop it
	// first, so a parent's config dir, proxy or key cannot leak into this one.
	b.WriteString("# Drop what a parent ak command exported\n")
	b.WriteString("if [ -n \"${AK_ENV_KEYS:-}\" ]; then\n")
	b.WriteString("  read -r -a ak_prev <<< \"$AK_ENV_KEYS\"\n")
	b.WriteString("  for ak_k in ${ak_prev[@]+\"${ak_prev[@]}\"}; do unset \"$ak_k\" 2>/dev/null || true; done\n")
	b.WriteString("fi\n\n")

	if l.Env.Deferred() {
		b.WriteString(renderKeyLookup(s))
	}

	b.WriteString("# Provider environment (managed by ak)\n")
	for _, kv := range l.Env.Set {
		b.WriteString(renderExport(kv))
	}
	// Explicitly unset provider keys that are not set: they are inherited from
	// the parent process on nested launches and would silently route to the
	// wrong provider if left behind.
	for _, k := range l.Env.Unset {
		fmt.Fprintf(&b, "unset %s || true\n", k)
	}
	fmt.Fprintf(&b, "ak_env_keys=%s\n", shellQuote(strings.Join(envKeys(l.Env.Set), " ")))
	b.WriteString("\n")

	// Under bash 3.2 an empty array expansion must be written as ${arr[@]+"${arr[@]}"}.
	fmt.Fprintf(&b, "ak_args=(%s)\n", shellWords(l.Args))
	if len(l.Variants) > 0 {
		b.WriteString("case \"$ak_variant\" in\n")
		for _, v := range l.Variants {
			if len(v.Env) == 0 && len(v.Args) == 0 {
				continue
			}
			fmt.Fprintf(&b, "  %s)\n", v.Name)
			for _, kv := range v.Env {
				b.WriteString("    " + renderExport(kv))
			}
			if len(v.Env) > 0 {
				fmt.Fprintf(&b, "    ak_env_keys=\"$ak_env_keys \"%s\n", shellQuote(strings.Join(envKeys(v.Env), " ")))
			}
			if len(v.Args) > 0 {
				fmt.Fprintf(&b, "    ak_args+=(%s)\n", shellWords(v.Args))
			}
			b.WriteString("    ;;\n")
		}
		b.WriteString("  *) ;;\n")
		b.WriteString("esac\n")
	}
	// AK_VARIANT is informational (e.g. for a status line) and never read
	// back, so a parent's variant cannot leak into a nested launch.
	b.WriteString("if [ -n \"${ak_variant:-}\" ]; then export AK_VARIANT=\"$ak_variant\"; else unset AK_VARIANT || true; fi\n")
	b.WriteString("export AK_ENV_KEYS=\"$ak_env_keys\"\n\n")

	if s.Pool {
		b.WriteString(renderGatewayStart(s))
	}
	b.WriteString(renderExec(s))
	return script(s.Kind, s.Name, b.String())
}

func envKeys(kvs []provider.KV) []string {
	keys := make([]string, len(kvs))
	for i, kv := range kvs {
		keys[i] = kv.Key
	}
	return keys
}

func renderExport(kv provider.KV) string {
	if kv.Secret && kv.Value == "" {
		return fmt.Sprintf("export %s=\"$ak_key\"\n", kv.Key)
	}
	return fmt.Sprintf("export %s=%s\n", kv.Key, shellQuote(kv.Value))
}

// renderKeyLookup resolves an api_key_ref through ak each time the command
// runs, so the plaintext key is never written to disk.
func renderKeyLookup(s Spec) string {
	var b strings.Builder
	b.WriteString("# Key resolved at launch (api_key_ref)\n")
	b.WriteString(assignWithOverride("ak_self", "AK_BIN", s.Self))
	b.WriteString("if [ ! -x \"$ak_self\" ]; then\n")
	b.WriteString("  ak_self=\"$(command -v ak || true)\"\n")
	b.WriteString("fi\n")
	fmt.Fprintf(&b, "if ! ak_key=\"$(\"$ak_self\" __key %s)\"; then\n", shellQuote(s.Name))
	fmt.Fprintf(&b, "  echo %s >&2\n", shellQuote("ak: cannot resolve the key for "+s.Name))
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n\n")
	return b.String()
}

// renderGatewayStart makes a pool command start `ak serve` in the background
// when nothing is listening yet, so a pool works without a separate terminal.
func renderGatewayStart(s Spec) string {
	var b strings.Builder
	b.WriteString("# A pool talks to ak's gateway: start it if it is not running\n")
	b.WriteString(assignWithOverride("ak_self", "AK_BIN", s.Self))
	b.WriteString("if [ ! -x \"$ak_self\" ]; then\n")
	b.WriteString("  ak_self=\"$(command -v ak || true)\"\n")
	b.WriteString("fi\n")
	b.WriteString("if ! \"$ak_self\" __gateway-up; then\n")
	b.WriteString("  exit 1\n")
	b.WriteString("fi\n\n")
	return b.String()
}

// renderExec generates the exec section.
// Pin the absolute path with a PATH fallback: non-interactive shells spawned by
// warren/tmux/VSCode may not include ~/.local/bin. Only the symlink level is
// pinned, with no symlink resolution into the version directory, otherwise the
// shims all point at an old version after the engine self-updates.
func renderExec(s Spec) string {
	var b strings.Builder
	b.WriteString(assignWithOverride("ak_bin", s.EnvVar, s.Bin))
	b.WriteString("if [ ! -x \"$ak_bin\" ]; then\n")
	fmt.Fprintf(&b, "  ak_bin=\"$(command -v %s || true)\"\n", s.BinName)
	b.WriteString("fi\n")
	b.WriteString("if [ -z \"$ak_bin\" ]; then\n")
	fmt.Fprintf(&b, "  echo 'ak: %s not found; check PATH or set %s' >&2\n", s.BinName, s.EnvVar)
	b.WriteString("  exit 127\n")
	b.WriteString("fi\n")
	b.WriteString("exec \"$ak_bin\" ${ak_args[@]+\"${ak_args[@]}\"} \"$@\"\n")
	return b.String()
}

// RenderAlias renders a standalone variant command that runs the provider's
// command with the variant as its first argument.
func RenderAlias(kind, name, target, variant string) string {
	body := fmt.Sprintf("set -euo pipefail\n\nexec %s %s \"$@\"\n", shellQuote(target), shellQuote(variant))
	return script(kind, name, body)
}

// assignWithOverride sets a variable to a default that an environment
// variable may override. The default is assigned on its own line: inside
// "${VAR:-'x'}" bash keeps the single quotes literally, which broke the path.
func assignWithOverride(name, envVar, def string) string {
	return fmt.Sprintf("%s=%s\nif [ -n \"${%s:-}\" ]; then %s=\"$%s\"; fi\n",
		name, shellQuote(def), envVar, name, envVar)
}
