package shim

import (
	"fmt"
	"strings"

	"github.com/abcdlsj/ak/internal/config"
	"github.com/abcdlsj/ak/internal/provider"
)

// Spec describes a shim to generate.
type Spec struct {
	Name    string // Provider name
	Kind    config.Kind
	Bin     string // Absolute path of the pinned engine binary; empty means rely on PATH
	BinName string // Engine command name, used as the PATH fallback
	EnvVar  string // Environment variable that overrides Bin, e.g. AK_CLAUDE_BIN
	Plan    provider.EnvPlan
	// Variants are the variant names the shim must recognize.
	Variants []string
	// VariantPlans holds each variant's delta over the base environment (claude).
	VariantPlans map[string][]provider.KV
	// Profile is passed as the codex --profile argument when non-empty.
	Profile string
	// ReasoningVariants turns variants into -c model_reasoning_effort= when true (codex).
	ReasoningVariants bool
}

// shellQuote wraps the value in single quotes and escapes inner single quotes,
// making any content safe. Bash performs no expansion inside single quotes, so
// $ ` " \ and newlines all stay literal.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Render renders the shim script, returning the complete file (including the marker line).
func Render(s Spec) string {
	var b strings.Builder

	body := renderBody(s)
	m := Marker{Kind: string(s.Kind), Provider: s.Name, Hash: hashBody(body)}

	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString(m.Line())
	b.WriteString("\n# DO NOT EDIT - generated by ak; changes are overwritten by the next `ak sync`.\n")
	b.WriteString(body)
	return b.String()
}

func renderBody(s Spec) string {
	var b strings.Builder
	b.WriteString("set -euo pipefail\n\n")

	if len(s.Variants) > 0 {
		b.WriteString(renderVariantDispatch(s))
	}

	b.WriteString("# Provider environment (managed by ak)\n")
	for _, kv := range s.Plan.Set {
		fmt.Fprintf(&b, "export %s=%s\n", kv.Key, shellQuote(kv.Value))
	}
	// Explicitly unset provider keys that are not set: they are inherited from
	// the parent process on nested launches and would silently route to the
	// wrong provider if left behind.
	for _, k := range s.Plan.Unset {
		fmt.Fprintf(&b, "unset %s || true\n", k)
	}
	b.WriteString("\n")

	if len(s.Variants) > 0 {
		b.WriteString(renderVariantApply(s))
	}

	b.WriteString(renderExec(s))
	return b.String()
}

// renderVariantDispatch generates first-argument variant detection.
// The first argument is consumed only on an exact variant match; anything else
// is passed through unchanged, so `ak-kimi -p "..."` still works.
func renderVariantDispatch(s Spec) string {
	var b strings.Builder
	b.WriteString("# Variant: consume the first argument only on an exact match\n")
	b.WriteString("ak_variant=\"${AK_VARIANT:-}\"\n")
	b.WriteString("if [ $# -gt 0 ]; then\n")
	b.WriteString("  case \"$1\" in\n")
	fmt.Fprintf(&b, "    %s)\n", strings.Join(s.Variants, "|"))
	b.WriteString("      ak_variant=\"$1\"; shift ;;\n")
	b.WriteString("  esac\n")
	b.WriteString("fi\n\n")
	return b.String()
}

// renderVariantApply generates the logic that applies the variant.
func renderVariantApply(s Spec) string {
	var b strings.Builder

	if s.ReasoningVariants {
		// codex: turn the variant into a -c override. Under bash 3.2 an empty
		// array expansion must be written as ${arr[@]+"${arr[@]}"}.
		b.WriteString("ak_extra=()\n")
		b.WriteString("if [ -n \"$ak_variant\" ]; then\n")
		b.WriteString("  ak_extra+=(-c \"model_reasoning_effort=\\\"$ak_variant\\\"\")\n")
		b.WriteString("fi\n\n")
		return b.String()
	}

	// claude: the variant overrides environment variables.
	b.WriteString("case \"$ak_variant\" in\n")
	for _, v := range s.Variants {
		kvs := s.VariantPlans[v]
		if len(kvs) == 0 {
			continue
		}
		fmt.Fprintf(&b, "  %s)\n", v)
		for _, kv := range kvs {
			fmt.Fprintf(&b, "    export %s=%s\n", kv.Key, shellQuote(kv.Value))
		}
		b.WriteString("    ;;\n")
	}
	b.WriteString("  *) ;;\n")
	b.WriteString("esac\n")
	b.WriteString("if [ -n \"$ak_variant\" ]; then export AK_VARIANT=\"$ak_variant\"; fi\n\n")
	return b.String()
}

// renderExec generates the exec section.
// Pin the absolute path with a PATH fallback: non-interactive shells spawned by
// warren/tmux/VSCode may not include ~/.local/bin. Only the symlink level is
// pinned, with no symlink resolution into the version directory, otherwise the
// shims all point at an old version after the engine self-updates.
func renderExec(s Spec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "ak_bin=\"${%s:-%s}\"\n", s.EnvVar, shellEnvDefault(s.Bin))
	b.WriteString("if [ ! -x \"$ak_bin\" ]; then\n")
	fmt.Fprintf(&b, "  ak_bin=\"$(command -v %s || true)\"\n", s.BinName)
	b.WriteString("fi\n")
	b.WriteString("if [ -z \"$ak_bin\" ]; then\n")
	fmt.Fprintf(&b, "  echo 'ak: %s not found; check PATH or set %s' >&2\n", s.BinName, s.EnvVar)
	b.WriteString("  exit 127\n")
	b.WriteString("fi\n")

	switch {
	case s.Profile != "" && s.ReasoningVariants:
		fmt.Fprintf(&b, "exec \"$ak_bin\" --profile %s ${ak_extra[@]+\"${ak_extra[@]}\"} \"$@\"\n",
			shellQuote(s.Profile))
	case s.Profile != "":
		fmt.Fprintf(&b, "exec \"$ak_bin\" --profile %s \"$@\"\n", shellQuote(s.Profile))
	default:
		b.WriteString("exec \"$ak_bin\" \"$@\"\n")
	}
	return b.String()
}

// shellEnvDefault renders the default part of ${VAR:-default}.
func shellEnvDefault(v string) string {
	if v == "" {
		return ""
	}
	return shellQuote(v)
}
