package shim

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"syscall"

	"github.com/abcdlsj/ak/internal/config"
	"github.com/abcdlsj/ak/internal/provider"
	"github.com/abcdlsj/ak/internal/secrets"
)

// shimMode is the permission mode of a shim. 700 rather than 755: the file
// embeds a plaintext key, so other users on the machine get no read access.
const shimMode = 0o700

// Action is the outcome for a single file.
type Action string

const (
	ActionCreated   Action = "created"
	ActionUpdated   Action = "updated"
	ActionUnchanged Action = "unchanged"
	ActionRemoved   Action = "removed"
	ActionSkipped   Action = "skipped"
)

// Result is one sync result.
type Result struct {
	Path   string
	Action Action
	Reason string // Explains why the file was skipped
}

// Report holds all results of one sync.
type Report struct {
	Results []Result
	DryRun  bool
}

// Counts summarizes results by action.
func (r Report) Counts() map[Action]int {
	m := map[Action]int{}
	for _, res := range r.Results {
		m[res.Action]++
	}
	return m
}

// Syncer generates and reclaims ak's artifacts.
type Syncer struct {
	Cfg      *config.Config
	Resolver secrets.Resolver
	DryRun   bool

	// CodexHome is the directory scanned for codex profile files. It is a field
	// rather than a hardcoded ~/.codex so tests stay hermetic instead of reaching
	// into the real home directory.
	CodexHome string
}

// Sync generates all shims and codex profiles, then reclaims orphaned artifacts.
func (s *Syncer) Sync() (Report, error) {
	rep := Report{DryRun: s.DryRun}

	binDir := config.ExpandHome(s.Cfg.Settings.BinDir)
	if !s.DryRun {
		if err := os.MkdirAll(binDir, 0o755); err != nil {
			return rep, err
		}
	}

	claudeBin := s.resolveBin(s.Cfg.Settings.ClaudeBin, "claude")
	codexBin := s.resolveBin(s.Cfg.Settings.CodexBin, "codex")

	// Record the artifacts that should exist this run; any other marked file of
	// the same kind is treated as an orphan.
	want := map[string]bool{}

	for _, name := range s.Cfg.Names() {
		p := s.Cfg.Providers[name]
		key, err := s.Resolver.Resolve(p)
		if err != nil {
			return rep, fmt.Errorf("secret for provider %s: %w", name, err)
		}

		switch p.Kind {
		case config.KindClaude:
			spec := s.claudeSpec(name, p, key, claudeBin)
			path := filepath.Join(binDir, s.Cfg.Settings.Prefix+name)
			want[path] = true
			rep.Results = append(rep.Results, s.writeFile(path, Render(spec), shimMode))

		case config.KindCodex:
			spec := s.codexSpec(name, p, key, codexBin)
			path := filepath.Join(binDir, s.Cfg.Settings.Prefix+name)
			want[path] = true
			rep.Results = append(rep.Results, s.writeFile(path, Render(spec), shimMode))

			profPath, content, err := s.codexProfile(name, p)
			if err != nil {
				return rep, err
			}
			want[profPath] = true
			rep.Results = append(rep.Results, s.writeFile(profPath, content, 0o600))
		}
	}

	orphans, err := s.collectOrphans(binDir, want)
	if err != nil {
		return rep, err
	}
	rep.Results = append(rep.Results, orphans...)

	sort.Slice(rep.Results, func(i, j int) bool { return rep.Results[i].Path < rep.Results[j].Path })
	return rep, nil
}

func (s *Syncer) claudeSpec(name string, p config.Provider, key, bin string) Spec {
	base := provider.ClaudeEnv(name, p, "", key)
	variants := provider.ClaudeVariants(p)

	// Compute each variant's delta over the base environment so only genuinely
	// changed keys are written.
	plans := map[string][]provider.KV{}
	baseMap := map[string]string{}
	for _, kv := range base.Set {
		baseMap[kv.Key] = kv.Value
	}
	for _, v := range variants {
		vp := provider.ClaudeEnv(name, p, v, key)
		var delta []provider.KV
		for _, kv := range vp.Set {
			if baseMap[kv.Key] != kv.Value {
				delta = append(delta, kv)
			}
		}
		if len(delta) > 0 {
			plans[v] = delta
		}
	}
	// Variants with no actual delta need not enter the dispatch.
	var effective []string
	for _, v := range variants {
		if len(plans[v]) > 0 {
			effective = append(effective, v)
		}
	}

	return Spec{
		Name: name, Kind: config.KindClaude,
		Bin: bin, BinName: "claude", EnvVar: "AK_CLAUDE_BIN",
		Plan: base, Variants: effective, VariantPlans: plans,
	}
}

func (s *Syncer) codexSpec(name string, p config.Provider, key, bin string) Spec {
	return Spec{
		Name: name, Kind: config.KindCodex,
		Bin: bin, BinName: "codex", EnvVar: "AK_CODEX_BIN",
		Plan:              provider.CodexEnv(name, p, key),
		Variants:          provider.CodexVariants(p),
		Profile:           provider.ProfileName(name),
		ReasoningVariants: true,
	}
}

// codexProfile renders ~/.codex/ak-<name>.config.toml.
func (s *Syncer) codexProfile(name string, p config.Provider) (string, string, error) {
	body, err := provider.CodexProfileTOML(name, p)
	if err != nil {
		return "", "", err
	}
	m := Marker{Kind: string(config.KindCodex), Provider: name, Hash: hashBody(string(body))}
	content := m.Line() + "\n# DO NOT EDIT - generated by ak; changes are overwritten by the next `ak sync`.\n" + string(body)
	path := filepath.Join(s.codexHome(), provider.ProfileName(name)+".config.toml")
	return path, content, nil
}

// writeFile writes idempotently: unchanged content is not written to disk and mtime is untouched.
func (s *Syncer) writeFile(path, content string, mode os.FileMode) Result {
	existing, err := os.ReadFile(path)
	switch {
	case err == nil && string(existing) == content:
		return Result{Path: path, Action: ActionUnchanged}
	case err == nil:
		// Exists but differs: only overwrite after confirming ak generated it,
		// otherwise a user's own script could be clobbered.
		if _, ok := readMarker(path); !ok {
			return Result{Path: path, Action: ActionSkipped,
				Reason: "exists and was not generated by ak"}
		}
		if s.DryRun {
			return Result{Path: path, Action: ActionUpdated}
		}
		if err := config.AtomicWrite(path, []byte(content), mode); err != nil {
			return Result{Path: path, Action: ActionSkipped, Reason: err.Error()}
		}
		return Result{Path: path, Action: ActionUpdated}
	case os.IsNotExist(err):
		if s.DryRun {
			return Result{Path: path, Action: ActionCreated}
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return Result{Path: path, Action: ActionSkipped, Reason: err.Error()}
		}
		if err := config.AtomicWrite(path, []byte(content), mode); err != nil {
			return Result{Path: path, Action: ActionSkipped, Reason: err.Error()}
		}
		return Result{Path: path, Action: ActionCreated}
	default:
		return Result{Path: path, Action: ActionSkipped, Reason: err.Error()}
	}
}

func (s *Syncer) collectOrphans(binDir string, want map[string]bool) ([]Result, error) {
	dirs := []struct {
		dir    string
		prefix string
	}{
		{binDir, s.Cfg.Settings.Prefix},
	}
	if codexHome := s.codexHome(); codexHome != "" {
		dirs = append(dirs, struct {
			dir    string
			prefix string
		}{codexHome, "ak-"})
	}

	var out []Result
	for _, d := range dirs {
		res, err := s.collectOrphansIn(d.dir, d.prefix, want)
		out = append(out, res...)
		if err != nil {
			return out, err
		}
	}
	return out, nil
}

// collectOrphansIn reclaims orphans within a single directory.
//
// All five conditions must hold before deletion; if any fails the file is skipped:
//  1. It lives in the given directory
//  2. Its name matches the prefix
//  3. It is a regular file, with no symlink following
//  4. Its owner is the current user
//  5. Its header carries a known ak:generated marker version
//
// ~/.local/bin holds user-owned tools such as warren, minions, agy and aicoding,
// so deleting the wrong file is extremely costly.
func (s *Syncer) collectOrphansIn(dir, prefix string, want map[string]bool) ([]Result, error) {
	var out []Result

	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		name := e.Name()
		if !strings.HasPrefix(name, prefix) {
			continue // Prefix mismatch: the first line of defense
		}
		path := filepath.Join(dir, name)
		if want[path] {
			continue
		}
		if res, ok := s.checkRemovable(path, e); !ok {
			out = append(out, res)
			continue
		}
		if s.DryRun {
			out = append(out, Result{Path: path, Action: ActionRemoved})
			continue
		}
		if err := os.Remove(path); err != nil {
			out = append(out, Result{Path: path, Action: ActionSkipped, Reason: err.Error()})
			continue
		}
		out = append(out, Result{Path: path, Action: ActionRemoved})
	}
	return out, nil
}

// checkRemovable runs every safety check before deletion.
func (s *Syncer) checkRemovable(path string, e os.DirEntry) (Result, bool) {
	// Use Lstat rather than Stat: do not follow symlinks, which could delete a
	// critical file through the link.
	fi, err := os.Lstat(path)
	if err != nil {
		return Result{Path: path, Action: ActionSkipped, Reason: err.Error()}, false
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		return Result{Path: path, Action: ActionSkipped, Reason: "is a symlink, refusing to follow"}, false
	}
	if !fi.Mode().IsRegular() {
		return Result{Path: path, Action: ActionSkipped, Reason: "not a regular file"}, false
	}
	if st, ok := fi.Sys().(*syscall.Stat_t); ok {
		if int(st.Uid) != os.Getuid() {
			return Result{Path: path, Action: ActionSkipped, Reason: "owner is not the current user"}, false
		}
	}
	m, ok := readMarker(path)
	if !ok {
		return Result{Path: path, Action: ActionSkipped, Reason: "no ak:generated marker"}, false
	}
	if m.Version > MarkerVersion {
		return Result{Path: path, Action: ActionSkipped,
			Reason: fmt.Sprintf("marker version v%d is newer than the supported v%d", m.Version, MarkerVersion)}, false
	}
	return Result{}, true
}

// codexHome returns the directory holding codex profiles.
// It is a field on Syncer rather than a hardcoded ~/.codex so tests stay hermetic
// instead of reaching into the real home directory.
func (s *Syncer) codexHome() string {
	if s.CodexHome != "" {
		return s.CodexHome
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".codex")
}

// resolveBin resolves the engine binary path.
// It takes only the layer found via PATH and does not call EvalSymlinks —
// claude's ~/.local/bin/claude is a symlink to versions/<ver>, and resolving it
// would leave every shim pointing at an old version after a self-update.
func (s *Syncer) resolveBin(configured, name string) string {
	if configured != "" {
		return config.ExpandHome(configured)
	}
	if p, err := exec.LookPath(name); err == nil {
		if abs, err := filepath.Abs(p); err == nil {
			return abs
		}
		return p
	}
	return ""
}
